<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GMAO.Application\GMAO.Application.csproj" />
    <ProjectReference Include="..\GMAO.Domain\GMAO.Domain.csproj" />
  </ItemGroup>

</Project>
